import type { Metadata } from "next";
import Providers from "@/components/QueryClientProvider";
import { Noto_Sans_Arabic, Roboto } from "next/font/google";
import "@/styles/abstracts/global.scss";

const roboto = Roboto({
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

const nastaliq = Noto_Sans_Arabic({
  weight: ["400"],
  subsets: ["arabic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
